In [1]:
import requests
from bs4 import BeautifulSoup
import csv

In [3]:
base_url = "http://quotes.toscrape.com/page/"  # Send a GET request to the current page
quotes_list=[]    # List to store scraped quote data
tag_list=[]       # Parse HTML content
author_list=[]   # List to store scraped quote data
tag_list=[]

In [5]:
import pandas as pd
page_no=1                                   # Starting URL for page 1
while True:
    url=f"{base_url}{page_no}/"
    response=requests.get(url)
    if response.status_code!=200:
        break
    soup=BeautifulSoup(response.text,"html.parser")

    quotes=soup.find_all("div",class_="quote")
    if not quotes:
        break
    for quote in quotes:
        text=quote.find("span",class_="text").text.strip()
        quotes_list.append(text)                             # Extract quote text

        author=quote.find("small",class_="author").text.strip()
        author_list.append(author)                           # Extract author name

        tags=quote.find_all("a",class_="tag")
        tag_name=[]                                           # Extract tags
        for tag in tags:
            tag_name.append(tag.text)
        tag_names_string=",".join(tag_name)
        tag_list.append(tag_names_string)
    page_no+=1                                           # Update URL to the next page

In [7]:
df = pd.DataFrame({
    "Author": author_list,
    "Quote": quotes_list,
    "Tags": tag_list                      # help of pandas save data into csv file
})

df.to_csv("quotes.csv", index=False, encoding="utf-8")
print(" Data saved to 'Quotes_Details.csv'")

 Data saved to 'Quotes_Details.csv'

In [9]:
df

,Author,Quote,Tags
0,Albert Einstein,“The world as we have created it is a process ...,"change,deep-thoughts,thinking,world"
1,J.K. Rowling,"“It is our choices, Harry, that show what we t...","abilities,choices"
2,Albert Einstein,“There are only two ways to live your life. On...,"inspirational,life,live,miracle,miracles"
3,Jane Austen,"“The person, be it gentleman or lady, who has ...","aliteracy,books,classic,humor"
4,Marilyn Monroe,"“Imperfection is beauty, madness is genius and...","be-yourself,inspirational"
...,...,...,...
95,Harper Lee,“You never really understand a person until yo...,better-life-empathy
96,Madeleine L'Engle,“You have to write the book that wants to be w...,"books,children,difficult,grown-ups,write,write..."
97,Mark Twain,“Never tell the truth to people who are not wo...,truth
98,Dr. Seuss,"“A person's a person, no matter how small.”",inspirational
99,George R.R. Martin,“... a mind needs books as a sword needs a whe...,"books,mind"